### ISSUE TITLE
coupling strength limit?

### ISSUE THREAD

**Issue by DemenzEchtbaer** [FaritaTasnim/comm#1]
Hi Farita,

Thank you for your inspiring article, and thank you for providing your code!
No real issue here, rather a simple question: in the energy switching scenario, can the couplings of the reservoirs be greater than 1? I accidentally input very large values for the two reservoirs in your code (35 for both) and got some oscillating behavior in the evolution of the ctmc, see attached pic.
![noisy_channel_ctmc](https://user-images.githubusercontent.com/70432349/230338466-bf13aa5e-87fc-4b2c-869f-51ff87b89a89.png)

Cheers,

**Comment by FaritaTasnim** [comment]
Hi there,

Yes feel free to set the couplings to any value you choose - however, do note that the assumptions of stochastic thermodynamics hold only in the overdamped limit. So it's possible that the results you get for the EP, etc., in scenarios where the coupling drives the system into the underdamped limit might not be accurate. Thanks for the question!

**Comment by DemenzEchtbaer** [comment]
Hey there,

Indeed, I hadn't thougt of this, thank you so much for your insights! Looking forward to your next articles :-)

Cheers,
